name: Bug report
description: Report a reproducible defect
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Precise steps to reproduce
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version/tag
      placeholder: v0.1.0
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: logs
    attributes:
      label: Logs/screenshots
